### ISSUE TITLE
 Agregar menú tipo Dropdown/sidebar.

### ISSUE THREAD

**Issue by JaMR94** [JaMR94/JaMR94.github.io#1]
- [x] Como administrador quisiera que la página de configuraciones tenga un menú expansivo que me lleve a diferentes secciones para hacer la configuración (artículos, precios, seguridad, etc).
- [x] #7

**Comment by abraham1669** [comment]
El tipo de menú que comentas puede ser un dropdown o un sidebar, según sea el caso y el que más les guste, Por qué esta Historia de Usuario se llama así? No sería mejor llamarla: Agregar menú tipo Dropdown/sidebar?

**Comment by GerardoCasC** [comment]
1. Si se refiere a una revisión/validación previa antes de la publicación no se está haciendo. Solo estabamos haciendo lluvia de ideas, no teníamos claro como se iban a subir lsa historias para el proceso del proyecto
2. Un pequeño error, se esta solucionando :D
3. Por ahora ninguno, apenas decidimos el maquetado que haremos
4. Entiendo... que es un project?
5. Solo ha pasado un día desde que lo pidió profe :(
