### ISSUE TITLE
Perfil de usuarios

### ISSUE THREAD

**Issue by kareng13** [JaMR94/JaMR94.github.io#17]
Como cliente
quiero que en la barra de tareas aparezca el perfil del cliente ya sea con una imagen o nombre en el que se desglose en un pequeño menu su perfil, carrito, cerrar sesion, etc, para que de esta manera este mas optimizada  todo lo que tenga relacion con los detalles del perfil, en el menu

**Comment by abraham1669** [comment]
Por qué esta Historia de Usuario se llama así? No sería mejor llamarla: Agregar Módulo de Perfil de Usuario?
