### ISSUE TITLE
Feedback para los usuarios

### ISSUE THREAD

**Issue by kareng13** [JaMR94/JaMR94.github.io#18]
Como cliente
quiero que al momento de querer iniciar sesion y ocurra algun error ya sea con el correo o contraseña, aparezca un texto mencionandolo, para que de esta manera el usuario sepa porque no puede iniciar sesion

**Comment by abraham1669** [comment]
Por qué esta Historia de Usuario se llama así? No sería mejor llamarla: ¿Mensajes de Error o Feedback para los usuarios?

**Comment by kareng13** [comment]
> Por qué esta Historia de Usuario se llama así? No sería mejor llamarla: ¿Mensajes de Error o Feedback para los usuarios?

Oh, siempre tan sabio
