### ISSUE TITLE
Registro regional 

### ISSUE THREAD

**Issue by Shadnucks** [JaMR94/JaMR94.github.io#6]
Como: Vendedor online independiente
Quiero: Saber las regiones y países de los compradores
Para: Identificar de que zonas de donde más se venden los productos para optimizar el coste y tiempo de las más populares.

**Comment by Creaky27** [comment]
No me pareció una mala idea, pero hay que ver primero como es que van a funcionar los vendedores. Si va a ser solo 1 o varios

**Comment by abraham1669** [comment]
Este requerimiento habrá que pasarlo a Backend, tienen que generarle un Issue, pidiendo que agreguen el campo país en las ventas o algo que permita obtener esa información
