### ISSUE TITLE
correcciones para el footer

### ISSUE THREAD

**Issue by Pudin-con-pasas-uwu** [JaMR94/JaMR94.github.io#91]
- [ ] todas las columnas deben estar en responsivo.

- [ ] si no se va a usar algún logo en donde falta la imagen, remplazarlo por un link para el inicio de la tienda.

**Comment by Creaky27** [comment]
Buenas tardes compañeros... Me surgió un problema y quería ver si me podían ayudar. @abraham1669 

![image](https://user-images.githubusercontent.com/102078259/225148065-3edd17e7-070d-45b3-8128-a7f3fb5212c7.png)

Ya intente corregirlo, pero aunque lo cambie de lugar, me aparece el mismo error en el primer import que aparece.
