### ISSUE TITLE
Checkout

### ISSUE THREAD

**Issue by Pudin-con-pasas-uwu** [JaMR94/JaMR94.github.io#96]
- [ ] que el checkout muestre el precio total, tomando en cuenta las cosas que se agregaron al carrito.

- [x] que cuando el cliente le de en pagar, se le envíe un correo con la confirmación de su compra.

**Comment by lokilaufeysonXD** [comment]
ya lo tengo echo que automaticamente envie un correo a una cuenta creada especialmente para saver los pedidos 
![image](https://user-images.githubusercontent.com/55563474/225540189-5e903d0a-a0a1-4dc9-8858-6bc0be7cdf09.png)
![image](https://user-images.githubusercontent.com/55563474/225540262-e24d90d4-3398-4690-88c4-dff19f222611.png)


y al cliente para que este sepa que su pedido ya fue revisado y esta siendo procesado 
![image](https://user-images.githubusercontent.com/55563474/225540450-c3d23df0-e461-4960-9e3f-5bb96d0a5bd6.png)

**Comment by lokilaufeysonXD** [comment]
solo porfa necesito que acepten mi pr para poder checar si el node meiler que me instale jala si no para reinstalarlo de otra manera que funciona al 100
